version: 2

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck

formatters:
  enable:
    - gofumpt

linters-settings:
  errcheck:
    # Ces patterns sont ignorés : defer close, unsetenv, k.Load
    exclude-functions:
      - (*sql.DB).Close
      - (*sql.Rows).Close
      - os.Unsetenv
      - (*koanf.Koanf).Load
